In [10]:
import numpy as np

Array_Size = 11
Array = np.zeros((Array_Size, Array_Size))

print('Basic array:\n', Array)

for i in range(Array_Size):
  for j in range(Array_Size):
    if (i == j):
      Array[i][j] = 1
    elif (i == Array_Size - j - 1):
      Array[i][j] = 1

print('\nNew array:\n', Array)

Basic array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

New array:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [16]:
import cv2
import numpy as np

H_G_1 = np.zeros((255, 255))
Width_H_1 = H_G_1.shape[1]
Height_H_1 = H_G_1.shape[0]

for i in range(Height_H_1):
    for j in range(Width_H_1):
        H_G_1[i][j] = ++j

cv2.imwrite('Horizontal_gradient_1.jpg', H_G_1)

H_G_2 = np.zeros((255, 255))
Width_H_2 = H_G_2.shape[0]
Height_H_2 = H_G_2.shape[1]

for i in range(Height_H_2):
    for j in range(Width_H_2):
        H_G_2[i][j] = Width_H_2 - j     

cv2.imwrite('Horizontal_gradient_2.jpg', H_G_2)


V_G_1 = np.zeros((255, 255))
Width_V_1 = V_G_1.shape[1]
Height_V_1 = V_G_1.shape[0]

for i in range(Width_V_1):
    for j in range(Height_V_1):
        V_G_1[i][j] = ++i

cv2.imwrite('Vertical_gradient_1.jpg', V_G_1)

V_G_2 = np.zeros((255, 255))
Width_V_2 = V_G_2.shape[1]
Height_V_2 = V_G_2.shape[0]

for i in range(Width_V_2):
    for j in range(Height_V_2):
        V_G_2[i][j] = Width_V_2 - i     

cv2.imwrite('Vertical_gradient_2.jpg', V_G_2)

True